AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: nodejs16.x
      Events:
        CreateTodoApi:
          Type: Api
          Properties:
            Path: /todos
            Method: post
        GetTodosApi:
          Type: Api
          Properties:
            Path: /todos
            Method: get
        GetTodoApi:
          Type: Api
          Properties:
            Path: /todos/{id}
            Method: get
        DeleteTodoApi:
          Type: Api
          Properties:
            Path: /todos/{id}
            Method: delete
  Policies:
    - AWSLambdaBasicExecutionRole