name: sam-node-project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Dependencies
        run: npm install

      - name: SAM Setup
        uses: aws-actions/setup-sam@v1
      
      - name: AWS Config Setup
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: SAM Build
        run: sam build --template-file ./template.yaml
      - name: Check contents of root directory
        run: ls -la ./
      - name: Check contents of build directory
        run: ls -la ./.aws-sam/build/

      # Upload build artifacts
      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sam-artifacts
          path: .aws-sam

  