name: sam-node-project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Dependencies
        run: npm install

      - name: SAM Setup
        uses: aws-actions/setup-sam@v1
      
      - name: AWS Config Setup
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: SAM Build
        run: sam build --template-file ./template.yaml
      - name: Check contents of root directory
        run: ls -la ./
      - name: Check contents of aws sam directory
        run: ls -la ./.aws-sam
      - name: Check contents of build directory
        run: ls -la ./.aws-sam/build/
      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sam-artifacts
          path: .aws-sam/build
  list-artifact:
    needs: build  
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: sam-artifacts
          path: ./downloaded-artifacts  
      - name: List contents of downloaded artifact
        run: ls -la ./downloaded-artifacts
  package:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Check contents of root directory
        run: ls -la ./

      - name: package
        run : sam package --template-file ./.aws-sam/build/template.yaml --s3-bucket data-b --output-template-file ./Template-packaged.yml

  deploy:
    name: SAM Deploy
    needs: [package]
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: sam deploy --no-fail-on-empty-changeset --stack-name sam-todo --template-file ./Template-packaged.yml --capabilities CAPABILITY_IAM --region us-east-1

  test:
    name: Testing
    needs: [deploy]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node Setup
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Restore NPM cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Dependencies 
        run: npm install
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: sam-artifacts
          path: .aws-sam

      - name: Test the code
        run: npm test


  