name: sam-node-project
on:
    push:
        branches:
            main
jobs:
    build:
        name: Initial Setup and Code Build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16]
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Node Setup
          uses: actions/setup-node@v1
          with:
            node-version: ${{matrix.node-version}}
        - name: Sam Setup
          uses: aws-actions/setup-sam@v1
        - name: AWS Config Setup
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        - name : SAM Build
          run: sam build
        - name : SAM Deploy
          run: sam  deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-todo --s3-bucket data-b --capabilities CAPABILITY_IAM --region us-east-1

          
    
